### PR TITLE
[FEATURE] Track reposters

### PR DESCRIPTION
**Pull request by aXises**
Uwu sworry this is my first PR, I am very inexperienced at C#.

I added a dictionary to the Post class to track the reporters amount, I don't know if I don't it right >///<.

### CODE REVIEW

**Comment by BradF-99** [comment]
will pull and test please hold

**Comment by aXises** [comment]
is this project dead?? been 200ms and no response

**Review by Assasindie — APPROVED** [review]
looks good 👍

**Review by Josh-Zhou — APPROVED** [review]

**Comment by Assasindie** [comment]
nvm looks bad 👎 doesnt compile

**Review by BradF-99 — CHANGES_REQUESTED** [review]
errors at line 64, 65, and 67 that ulong cannot be converted to string and the property / indexer at line 79 cannot be assigned to.

**Review by Assasindie — CHANGES_REQUESTED** [review]
please fix the conversion errors from ulong to string

**Comment by aXises** [comment]
@BradF-99 @Assasindie does it need to compile?

**Comment by BradF-99** [comment]
> 
> 
> @BradF-99 @Assasindie does it need to compile?

preferably but not absolutely required

**Comment by Josh-Zhou** [comment]
ah yes it doesn't compile pls fix

**Comment by Josh-Zhou** [comment]
I agree

**Comment by Assasindie** [comment]
compiles correctly now!

**Comment by BradF-99** [comment]
ok I check again

**Review by Josh-Zhou — DISMISSED** [review]

**Review by BradF-99 — CHANGES_REQUESTED** [review]
Throws unhandled exception: 

```
MongoDB.Bson.BsonSerializationException: When using DictionaryRepresentation.Document key values must serialize as strings.
   at MongoDB.Driver.Core.Connections.BinaryConnection.SendMessagesAsync(IEnumerable`1 messages, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatchAsync(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatchesAsync(RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteBatchAsync(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOneAsync(TDocument document, InsertOneOptions options, Func`3 bulkWriteAsync)
   at RepostDetector.Bot.Handlers.MessageReceivedHandler.Handle(SocketMessage arg) in G:\RepostDetector\RepostDetector.Bot\Handlers\MessageReceivedHandler.cs:line 92
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Review by Josh-Zhou — APPROVED** [review]

**Comment by Assasindie** [comment]
we got there in the end

**Review by Assasindie — APPROVED** [review]

**Comment by aXises** [comment]
Thanks everyone 🥰🥰!!

**Pull request merged**
